spring:
  profiles:
    active: dev
  application:
    name: freewheelin-app

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
  use-management-port: false
  auto-tag-classes: true
  override-with-generic-response: false
  write-only-properties: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

